###
GET {{host}}/device/monitor/light/box

###
GET {{host}}/device/monitor/light/status

###
GET {{host}}/device/monitor/light/config

###
GET {{host}}/device/monitor/light/page?current=1&size=10&onlineStatus=1

###
GET {{host}}/device/monitor/light/page?current=1&size=10&workStatus=1

###
POST {{host}}/device/monitor/light/work?action=0&deviceId=1

###